- name: Provision DigitalOcean droplets
  hosts: localhost
  gather_facts: no
  vars:
    do_keys:
      - name: gangaram.d@optit.co
        pub_key_file: "~/.ssh/id_rsa.pub"
    do_droplets:
      - name: ansibletest
        port: 4222
        user: admin
        ssh_key_name: gangaram.d@optit.co
    do_inventory_file: ~/.ansible/hosts

  roles:
    - do_droplet_creation
