[local]
localhost ansible_connection=local

[digitalocean]
ansible-2 ansible_host=68.183.65.132 ansible_user=admin ansible_port=80
ansible-1 ansible_host=46.101.234.29 ansible_user=admin ansible_port=443

[all:vars]
ansible_python_interpreter=/usr/bin/python
ansible_host_key_checking=False