- name: Get the volume name
  shell: ls /dev/disk/by-id/ | grep -v part
  register: volume_name_raw
  tags:
    - mount-storage  

- set_fact:
    volume_name: "{{ volume_name_raw.stdout }}"
  tags:
    - mount-storage    

- name: Check if the volume is already setup
  command: grep '{{ volume_name }}' /etc/fstab -q
  register: volume_present
  ignore_errors: True
  tags:
    - mount-storage  

- name: Label the volume
  command: parted /dev/disk/by-id/{{ volume_name }} mklabel gpt
  when: volume_present is failed
  tags:
    - mount-storage

- name: Create an ext4 partition
  command: parted -a opt /dev/disk/by-id/{{ volume_name }} mkpart primary ext4 0% 100%
  when: volume_present is failed
  tags:
    - mount-storage  

- name: Build the ext4 metadata
  command: mkfs.ext4 /dev/disk/by-id/{{ volume_name }}-part1
  when: volume_present is failed
  tags:
    - mount-storage  

- name: Create the mount point
  command: mkdir -p /mnt/data
  when: volume_present is failed
  tags:
    - mount-storage  

- name: Mount volume read-write
  mount:
    path: /mnt/data
    src: /dev/disk/by-id/{{ volume_name }}-part1
    fstype: ext4
    opts: defaults,discard
    state: mounted
  tags:
    - mount-storage